In [52]:
import pandas as pd

df = pd.read_csv("../data/raw/311_Service_Requests_from_2020_to_Present_20260611.csv")

/var/folders/gr/4qz4cnhs6t994qx17kmkddwm0000gn/T/ipykernel_95114/3624492426.py:3: DtypeWarning: Columns (9,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/311_Service_Requests_from_2020_to_Present_20260611.csv")

In [53]:
# picking important columns
print(df.columns.to_list())

df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')
print(df.columns.to_list())

Columns_To_Keep = ['unique_key', 'created_date', 'closed_date', 'agency', 'agency_name', 'borough', 'problem_(formerly_complaint_type)', 'status']

df_clean = df[Columns_To_Keep].copy()

['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name', 'Problem (formerly Complaint Type)', 'Problem Detail (formerly Descriptor)', 'Additional Details', 'Location Type', 'Incident Zip', 'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2', 'Intersection Street 1', 'Intersection Street 2', 'Address Type', 'City', 'Landmark', 'Facility Type', 'Status', 'Due Date', 'Resolution Description', 'Resolution Action Updated Date', 'Community Board', 'Council District', 'Police Precinct', 'BBL', 'Borough', 'X Coordinate (State Plane)', 'Y Coordinate (State Plane)', 'Open Data Channel Type', 'Park Facility Name', 'Park Borough', 'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment', 'Latitude', 'Longitude', 'Location']
['unique_key', 'created_date', 'closed_date', 'agency', 'agency_name', 'problem_(formerly_complaint_type)', 'problem_detail_(formerly_descriptor)', 'additional_details', 'location_type', 'incident_zip', 'incident_address', 'street_name', 'cross_street_1', 'cross_street_2', 'intersection_street_1', 'intersection_street_2', 'address_type', 'city', 'landmark', 'facility_type', 'status', 'due_date', 'resolution_description', 'resolution_action_updated_date', 'community_board', 'council_district', 'police_precinct', 'bbl', 'borough', 'x_coordinate_(state_plane)', 'y_coordinate_(state_plane)', 'open_data_channel_type', 'park_facility_name', 'park_borough', 'vehicle_type', 'taxi_company_borough', 'taxi_pick_up_location', 'bridge_highway_name', 'bridge_highway_direction', 'road_ramp', 'bridge_highway_segment', 'latitude', 'longitude', 'location']

In [54]:
# Renaming a few

df_clean = df_clean.rename(columns={
    'unique_key' : 'request_id',
    'problem_(formerly_complaint_type)' : 'complaint_type'

    })

df_clean

,request_id,created_date,closed_date,agency,agency_name,borough,complaint_type,status
0,63578322,01/01/2025 12:59:59 AM,01/01/2025 12:18:24 PM,NYPD,New York City Police Department,MANHATTAN,Noise - Residential,Closed
1,63582809,01/01/2025 12:59:56 AM,01/01/2025 01:01:47 AM,NYPD,New York City Police Department,QUEENS,Noise - Residential,Closed
2,63576488,01/01/2025 12:59:55 AM,01/02/2025 05:09:54 PM,NYPD,New York City Police Department,BRONX,Noise - Residential,Closed
3,63578837,01/01/2025 12:59:54 AM,01/01/2025 01:50:11 AM,NYPD,New York City Police Department,QUEENS,Blocked Driveway,Closed
4,63572902,01/01/2025 12:59:22 AM,01/01/2025 02:06:14 AM,NYPD,New York City Police Department,BRONX,Illegal Parking,Closed
...,...,...,...,...,...,...,...,...
3456999,59890746,01/01/2024 01:00:54 AM,01/01/2024 01:07:50 AM,NYPD,New York City Police Department,MANHATTAN,Noise - Street/Sidewalk,Closed
3457000,59892601,01/01/2024 01:00:42 AM,01/01/2024 01:03:29 AM,NYPD,New York City Police Department,MANHATTAN,Noise - Residential,Closed
3457001,59892033,01/01/2024 01:00:24 AM,01/01/2024 05:38:59 AM,NYPD,New York City Police Department,MANHATTAN,Noise - Commercial,Closed
3457002,59889309,01/01/2024 01:00:04 AM,01/01/2024 03:22:18 AM,NYPD,New York City Police Department,MANHATTAN,Illegal Parking,Closed
3457003,59891565,01/01/2024 01:00:03 AM,01/01/2024 01:04:38 AM,NYPD,New York City Police Department,BROOKLYN,Noise - Commercial,Closed

In [55]:
# Remove Dups and nulls and check for spaces, etc.

df_clean = df_clean.dropna(subset=[
    "request_id",
    "created_date",
    "agency",
    "agency_name",
    "borough",
    "complaint_type",
    'status'
]) # skiped over closed_date because not all case's are closed.
df_clean = df_clean.drop_duplicates()
df_clean.shape

(3457004, 8)

In [ ]:
# cleaning date format for better calulations later on.

df_clean["created_date"] = pd.to_datetime(df_clean["created_date"], errors="coerce")
df_clean["closed_date"] = pd.to_datetime(df_clean["closed_date"], errors="coerce")

df_clean

/var/folders/gr/4qz4cnhs6t994qx17kmkddwm0000gn/T/ipykernel_95114/2353416807.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean["created_date"] = pd.to_datetime(df_clean["created_date"], errors="coerce")

,request_id,created_date,closed_date,agency,agency_name,borough,complaint_type,status
0,63578322,2025-01-01 00:59:59,2025-01-01 12:18:24,NYPD,New York City Police Department,MANHATTAN,Noise - Residential,Closed
1,63582809,2025-01-01 00:59:56,2025-01-01 01:01:47,NYPD,New York City Police Department,QUEENS,Noise - Residential,Closed
2,63576488,2025-01-01 00:59:55,2025-01-02 17:09:54,NYPD,New York City Police Department,BRONX,Noise - Residential,Closed
3,63578837,2025-01-01 00:59:54,2025-01-01 01:50:11,NYPD,New York City Police Department,QUEENS,Blocked Driveway,Closed
4,63572902,2025-01-01 00:59:22,2025-01-01 02:06:14,NYPD,New York City Police Department,BRONX,Illegal Parking,Closed
...,...,...,...,...,...,...,...,...
3456999,59890746,2024-01-01 01:00:54,2024-01-01 01:07:50,NYPD,New York City Police Department,MANHATTAN,Noise - Street/Sidewalk,Closed
3457000,59892601,2024-01-01 01:00:42,2024-01-01 01:03:29,NYPD,New York City Police Department,MANHATTAN,Noise - Residential,Closed
3457001,59892033,2024-01-01 01:00:24,2024-01-01 05:38:59,NYPD,New York City Police Department,MANHATTAN,Noise - Commercial,Closed
3457002,59889309,2024-01-01 01:00:04,2024-01-01 03:22:18,NYPD,New York City Police Department,MANHATTAN,Illegal Parking,Closed
3457003,59891565,2024-01-01 01:00:03,2024-01-01 01:04:38,NYPD,New York City Police Department,BROOKLYN,Noise - Commercial,Closed